version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: betalent
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adonis:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: adonis
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: betalent
      TZ: UTC
      LOG_LEVEL: info
      APP_KEY: dje93LCUQdRWl3s8JCh46-KlQgT0ymxw
      HOST: 0.0.0.0

volumes:
  mysql-data:
